const TRADE_INTERVAL_SECS=7;
const AMOUNT_TO_TRADE = 0.01;//ETH
const INVESTMENT=10;//EUR
const ERROR_TOLERANCE=100;
const PRODUCT_TYPE='ETH-EUR';
const TRADE_SAMPLE_SIZE=7;

exports.TRADE_INTERVAL_SECS = TRADE_INTERVAL_SECS;
exports.AMOUNT_TO_TRADE = AMOUNT_TO_TRADE;
exports.INVESTMENT = INVESTMENT;
exports.ERROR_TOLERANCE = ERROR_TOLERANCE;
exports.PRODUCT_TYPE = PRODUCT_TYPE;
exports.TRADE_SAMPLE_SIZE = TRADE_SAMPLE_SIZE;

